# docker-compose.yml
# Este archivo orquesta múltiples contenedores Docker para la aplicación.

version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=sqlite:///pet_store.db

